//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModule
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public System.DateTimeOffset DateAdded { get; set; }
        public string Text { get; set; }
        public CommentType CommentType { get; set; }
        public Nullable<System.DateTimeOffset> ReminderDate { get; set; }
        public int TaskId { get; set; }
    
        public virtual Task Task { get; set; }
    }
}
