//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModule
{
    using System;
    
    public enum CommentType : int
    {
        General = 0,
        Reminder = 1,
        Status = 2
    }
}
