//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementModule
{
    using System;
    
    public enum TaskStatus : int
    {
        Active = 0,
        Completed = 1,
        Cancelled = 2
    }
}
